name = "soundforyou-site"
compatibility_date = "2025-09-26"
# Required for Node APIs in Functions (crypto.subtle for hashing/JWT)
compatibility_flags = ["nodejs_compat"]

# Static assets from root (no build needed)
pages_build_output_dir = "."

# D1 Database binding (enables env.DB in Functions for auth/DB operations)
[[d1_databases]]
binding = "DB"  # This must match what your Functions code uses (e.g., env.DB)
database_name = "soundforyou_db"  # Matches the name you created
database_id = "b17fc148-4348-41a7-a0f1-ebca3bffbb80"

# R2 for sound file storage/uploads
[[r2_buckets]]
binding = "SOUNDS"
bucket_name = "soundforyou-sounds"

# Environment variables for production
[vars]
JWT_SECRET = "a4b6c8d0e2f415263748596a7b8c9d0e11223344556677889900aabbccddeeffa4b6c8d0e2f415263748596a7b8c9d0e11223344556677889900aabbccddeeff"
TURNSTILE_SECRET = "0x4AAAAAAB3apnxDc_U3LAOAbAg1dmxAbkI"
CONTACT_TO = "darraghfmurray@gmail.com"
