name = "soundforyou-site"
compatibility_date = "2025-09-26"
# Required for Node APIs in Functions (crypto.subtle for hashing/JWT)
compatibility_flags = ["nodejs_compat"]

# Static assets from root (no build needed)
pages_build_output_dir = "."

# D1 Database binding (enables env.DB in Functions for auth/DB operations)
[[d1_databases]]
binding = "DB"  # This must match what your Functions code uses (e.g., env.DB)
database_name = "soundforyou_db"  # Matches the name you created
database_id = "b17fc148-4348-41a7-a0f1-ebca3bffbb80"

# R2 for sound file storage/uploads
[[r2_buckets]]
binding = "SOUNDS"
bucket_name = "soundforyou-sounds"

# Functions configuration (ensures /functions dir is scanned correctly)
[functions]
directory = "functions"

# Environment vars aren't in toml; set in Dashboard for secrets (overrides local)
# But for local dev: Add [env.production] if needed
