name = "soundforyou-site"
compatibility_date = "2025-09-26"
# If you use Node APIs in Functions, uncomment this:
# compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install && npm run build"

[pages]
production_branch = "main"
pages_build_output_dir = "dist"
