name = "soundforyou-site"
compatibility_date = "2025-09-26"
# If you use Node APIs in Functions, uncomment this:
# compatibility_flags = ["nodejs_compat"]

[pages]
# Optional but helpful if deploying from Git
production_branch = "main"

# Static assets directory (Pages will upload this path)
# If you later build to a folder like "dist" or "build", change to that path.
[assets]
directory = "."
