name = "soundforyou-site"
compatibility_date = "2025-09-26"
# If you use Node APIs in Functions, uncomment this:
# compatibility_flags = ["nodejs_compat"]

[pages]
build_output_dir = "dist"
build_command = "npm run build"
production_branch = "main"
