name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]  # Triggers on push to main
  pull_request:
    branches: [main]  # Optional: Preview on PRs

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Clones repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Or your version; stable for Wrangler

      - name: Install dependencies (if package.json exists)
        run: npm ci  # Or npm install; skips if no package.json

      - name: Build (skip if no build needed)
        run: |
          # Optional: If you add package.json with "build" script later
          # npm run build
          echo "No build needed; serving from root"
        # This creates dist if you implement it; otherwise, use . below

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3  # Official action for Wrangler; handles npx
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # Pulls from secret
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}  # Optional if not in token
          command: pages publish . --project-name soundforyou-site  # Use . for root; change to dist if building
          # wranglerVersion: "3"  # Pins to stable v3.x
